server:
  port: 88
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guigu-auth?serverTimezone=GMT%2B8
    username: root
    password: 123456
